In [30]:
import numpy as np


a = np.array(0.00088477, dtype='f')
b = [(1,a), (2,a), (6,a), (3,a)]
c = [(1, -21), (30, -20), (300, -10), (300, -10)]

In [31]:
m,n  = zip(*b)
n



(array(0.00088477, dtype=float32),
 array(0.00088477, dtype=float32),
 array(0.00088477, dtype=float32),
 array(0.00088477, dtype=float32))

In [32]:
m = np.asarray(m)
n = np.asarray(n)

n
np.save("n.npy", n)


In [33]:
np.stack((m,n), axis = 0)

array([[1.00000000e+00, 2.00000000e+00, 6.00000000e+00, 3.00000000e+00],
       [8.84770008e-04, 8.84770008e-04, 8.84770008e-04, 8.84770008e-04]])

In [34]:
x = np.load("n.npy")

In [35]:
x

array([0.00088477, 0.00088477, 0.00088477, 0.00088477], dtype=float32)

In [54]:
np.savetxt('test.out', x, delimiter=',') 

In [37]:
with open("a.npy", "a") as f:
    np.savetxt(f, x)

In [57]:
y = np.loadtxt('test.out')

In [58]:
y


array([0.00088477, 0.00088477, 0.00088477, 0.00088477, 0.00088477,
       0.00088477, 0.00088477, 0.00088477])

In [3]:
x_loss = np.load("x_loss.npy")

In [4]:
x_loss

array([10001, 10002, 10003, ..., 12998, 12999, 13000])

In [13]:
len(x_loss)

n

array([0.00088477, 0.00088477, 0.00088477, 0.00088477], dtype=float32)

In [71]:
with open("data/a.txt", "a") as f:
    np.savetxt(f, n)
with open("data/a.txt", "a") as f:
    np.savetxt(f, n)

In [72]:
b = np.loadtxt("data/a.txt")

In [73]:
b

array([0.00088477, 0.00088477, 0.00088477, 0.00088477, 0.00088477,
       0.00088477, 0.00088477, 0.00088477, 0.00088477, 0.00088477,
       0.00088477, 0.00088477])

In [69]:
with open("a", "a") as f:
    np.save(f, )
    

TypeError: write() argument must be str, not bytes

In [61]:
b = np.load("a.npy")

In [63]:
b[0] = 0.00088

In [64]:
b


array([0.00088   , 0.00088477, 0.00088477, 0.00088477], dtype=float32)

In [65]:
with open("a.npy", "ab") as f:
    np.save(f, b)
    

In [66]:
b = np.load("a.npy")
b

array([0.00088477, 0.00088477, 0.00088477, 0.00088477], dtype=float32)